// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/THIRD_PARTY_NOTICES.txt"
    | "/_locales/zh_CN/messages.json"
    | "/background.js"
    | "/content-scripts/baidu.js"
    | "/icons/searchlens-128.png"
    | "/icons/searchlens-16.png"
    | "/icons/searchlens-32.png"
    | "/icons/searchlens-48.png"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
